feat: enable parallelism on top of new architecture
callstackincubator/fabrice-ai pull request #111
Opened 2024-12-12 16:10 UTC by grabbou

We let agents run in parallel, but then, we combine them into sequential order, like they run in order. 

I will improve type definitions in a follow-up, as well as add necessary helpers to make sure this is easy to understand. However, it can be tested right now. 

Need to add some configuration for "parallelism" of course.

Attaching the output.

![CleanShot 2024-12-12 at 19 09 21@2x](https://github.com/user-attachments/assets/9929eb24-6a50-4697-acf1-deecf2b1c68e)

2024-12-12 16:17 UTC, pkarw commented on packages/framework/src/agent.ts
> +          messages: [state.messages[0], agentResponse],
it's not clear what `state.messages[0]` is - lets add a named helper to extract this message or at least comment - this magic numbers is a nightmare for further maintainers

2024-12-12 16:18 UTC, pkarw commented on packages/framework/src/agents/supervisor.ts
>              1. Each task should be self-contained and achievable
I'd suggest another rule: Tasks should not depend on each other / each other results to avoid a potential clash/race conditions.

2024-12-12 16:19 UTC, pkarw requested changes
Generally this is great. Some minor changes requested.

2024-12-12 16:21 UTC, pkarw commented
Plus, maybe parallelism should be explicitly enabled/disabled because I can imagine some kinds of workflows that cannot be processed in parallel - I mean this kind of scenario where there are a few steps to be executed, but the next steps depend on the previous result. In this case, there's a significant risk that the supervisor won't get these details and split the tasks. There should be a way to prevent this from happening. 

Another thing is to have a configurable number of parallel tasks (children) at hand.

2024-12-12 16:32 UTC, pkarw approved these changes
Helpers are great. Parallelism probably need to be more harnessed with max-concurrency etc. But in general this is cool

2024-12-12 16:34 UTC, grabbou commented
> Plus, maybe parallelism should be explicitly enabled/disabled because I can imagine some kinds of workflows that cannot be processed in parallel - I mean this kind of scenario where there are a few steps to be executed, but the next steps depend on the previous result. In this case, there's a significant risk that the supervisor won't get these details and split the tasks. There should be a way to prevent this from happening.
> 
> Another thing is to have a configurable number of parallel tasks (children) at hand.

Should parallelism be enabled by default? Or shall we consider it advanced feature?
What should be default parallelism value?

2024-12-13 13:44 UTC, grabbou commented on packages/framework/src/messages.ts
> +export const getSteps = (conversation: Message[]): Message[] => {
@pkarw should we leave this function as returning an array of steps, or should we change its signature to return string, and construct this message here? I am leaning towards the latter!

2024-12-13 14:02 UTC, pkarw commented
@grabbou parallelism should be disabled for now - until we stabilize the `resourcePlanner` and `supervisor` so they're not getting stucked/looped over (see: #112). So - let's work on enabling it next week :D 

Parallelism is clearly `quality` not `quantity` improvement. We still need some `quantity` improvements (like Ollama support)

2024-12-13 14:15 UTC, pkarw approved these changes

2024-12-13 14:16 UTC, pkarw commented on packages/framework/src/messages.ts
> +export const getSteps = (conversation: Message[]): Message[] => {
I also think Steps are more like a single message - because so far, messages somehow mimic the interactions between different actors, and the list of steps is just one side story (?)

2024-12-13 14:25 UTC, grabbou commented
Yup, there's no parallel support at this point, so we're good here!

2024-12-13 14:59 UTC, pkarw approved these changes
All good. All examples pass.

2024-12-13 15:00 UTC, merged

2024-12-13 15:08 UTC, grabbou commented on packages/framework/src/messages.ts
> +export const getSteps = (conversation: Message[]): Message[] => {
Will send a follow-up converting it into a message